class AlreadyLoggedInError(Exception):
    """Исключение, возникающее при попытке повторного входа."""
    pass
